// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1680254125);
user_pref("app.update.lastUpdateTime.background-update-timer", 1680254365);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1680254245);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1680275860);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1680254485);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20220930170901");
user_pref("extensions.lastAppVersion", "6.0.15");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.automaticSnapshots", false);
user_pref("extensions.zotero.baseAttachmentPath", "/data/tubCloud/home/zotero");
user_pref("extensions.zotero.dataDir", "/home/denis/.zotero/data-directory");
user_pref("extensions.zotero.export.bibliographySettings", "{\"mode\":\"bibliography\",\"method\":\"copy-to-clipboard\"}");
user_pref("extensions.zotero.export.lastStyle", "http://www.zotero.org/styles/vancouver");
user_pref("extensions.zotero.export.noteQuickCopy.setting", "{\"mode\":\"export\",\"id\":\"a45eca67-1ee8-45e5-b4c6-23fb8a852873\"}");
user_pref("extensions.zotero.fileHandler.pdf", "/usr/bin/zathura");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastAbstractExpand", false);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{\"width\":\"324\"},\"zotero-tags-splitter\":{\"state\":\"\"},\"zotero-tag-selector-container\":{\"height\":\"264\"},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{\"width\":\"1246\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"338\",\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 5);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"hxyPdAfs\"},{\"id\":\"L1\",\"sessionID\":\"yJLDGVGa\"}]");
user_pref("extensions.zotero.saveRelativeAttachmentPath", true);
user_pref("extensions.zotero.sync.librariesToSkip", "[]");
user_pref("extensions.zotero.sync.server.username", "denisalevi");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.installed", true);
user_pref("extensions.zoteroOpenOfficeIntegration.version", "6.0.2.SA.6.0.15");
user_pref("extensions.zotfile.add_etal", false);
user_pref("extensions.zotfile.dest_dir", "/data/tubCloud/home/zotero/original");
user_pref("extensions.zotfile.import", false);
user_pref("extensions.zotfile.max_authors", 1);
user_pref("extensions.zotfile.renameFormat", "{%a - }{%y - }{%t}");
user_pref("extensions.zotfile.source_dir", "/home/denis/Downloads");
user_pref("extensions.zotfile.source_dir_ff", false);
user_pref("extensions.zotfile.userInput", true);
user_pref("extensions.zotfile.userInput_Default", "");
user_pref("extensions.zotfile.version", "5.1.2");
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1680255145);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1680255145);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1679480803);
