#!/bin/sh
while read file
do
    case "$1" in
        "h")
            # help
            scriptpath="$0"
            rm_spaces='s/^\s*//'  # spaces at start of line
            rm_sep='/^--$/d'  # remove grep seperator lines (--)
            rm_quotes='s/[")]//g'  # remove all " and )
            join_hash_lines=':begin;$!N;s/\n\#/ /;tbegin;P;D'
            msg=$(grep -A 1 " \".\")" $scriptpath | sed -e "$rm_spaces" -e "$rm_sep" -e "$rm_quotes" | sed "$join_hash_lines")
            notify-send -i "$(readlink -f "$file")" "$msg" &
            ;;
        "w")
            # wallpaper
            setbg "$file" &
            ;;
        "c")
            # copy
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
            ;;
        "m")
            # move
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            newname="$(dmenu -l 20 -i -p "Rename $file to (blank keeps name) ..." | sed "s|~|$HOME|g")"
            [ -z "$newname" ] && destfile=$destdir || destfile=$destdir/$newname
            [ -z "$destfile" ] && exit
            mv "$file" "$destfile" && notify-send -i "$(readlink -f "$file")" "$file moved to $destfile." &
            ;;
        "n")
            # rename
            [ -z "$newname" ] && newname="$(dmenu -l 20 -i -p "Rename $file to?" | sed "s|~|$HOME|g")"
            [ -z "$newname" ] && exit
            destfile=$PWD/$newname
            [ -z "$destfile" ] && exit
            mv "$file" "$destfile" && notify-send -i "$(readlink -f "$file")" "$file moved to $destfile." &
            ;;
        "r")
            # rotate clockwise
            # 🔃
            convert -rotate 90 "$file" "$file" ;;
        "R")
            # rotate counter-clockwise
            # 🔄
            convert -rotate -90 "$file" "$file" ;;
        "f")
            # mirror image
            convert -flop "$file" "$file" ;;
        # just copies image name
        #"y")
        #	echo -n "$file" | xclip -selection clipboard &&
        #	notify-send "$file copied to clipboard" & ;;
        "y")
            # yank image to clipboard
            xclip -selection clipboard -t image/png -i "$(readlink -f "$file")" && notify-send "image $file copied to clipboard" &
            ;;
        "Y")
            # yank path to image to clipboar
            echo -n "$(readlink -f "$file")" | xclip -selection clipboard && notify-send "$(readlink -f "$file") copied to clipboard" &
            ;;
        "d")
            # delete file
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "g")
            # open file in gimp
            ifinstalled gimp && gimp "$file" &
            ;;
    esac
done
