#!/bin/bash

# $1 firefox config as shown in about:config, e.g. browser.search.defaulturl
# $2 preference value, e.g. '"https://duckduckgo.com"'

# get path to default firefox profile
# adapted from https://askubuntu.com/a/354907
cd ~/.mozilla/firefox/
if [[ $(grep '\[Profile[^0]\]' profiles.ini) ]]
then
    PROFFOLDER=$( \
        grep -E '^\[Profile|^Path|^Default' profiles.ini \
        | grep -1 '^Default=1' \
        | grep '^Path' \
        | cut -c6- \
    )
else
    PROFFOLDER=$( \
        grep 'Path=' profiles.ini \
        | sed 's/^Path=//' \
    )
fi

USERJS=~/.mozilla/firefox/$PROFFOLDER/user.js

# set preference in user.js file in default firefox browser directory
# adapted from https://askubuntu.com/a/715465
# replace existing preference with new value
sed -i 's/user_pref("'$1'",.*);/user_pref("'$1'",'$2');/' $USERJS
# if preference was not existing, add it with specified value
grep -q $1 $USERJS || echo "user_pref(\"$1\",$2);" >> $USERJS
