#!/bin/sh
# toggle bluetooth on/off

#if rfkill -ro Soft list bluetooth | grep -q "^blocked"
#state=$(bluetoothctl -- show | grep Powered | awk '{print $2}')
if bluetoothctl -- show | grep -q "Powered: no"
then
  	#sudo rfkill unblock bluetooth
	#echo "ON"
	bluetoothctl -- power on
else
  	#sudo rfkill block bluetooth
	#echo "OFF"
	bluetoothctl -- power off
fi
